### ISSUE TITLE
pypiwin32 para rodar em Windows

### ISSUE THREAD

**Issue by rodolfo-viana** [turicas/mandados-de-prisao#1]
Só um lembrete a partir de um erro que encontrei tentando rodar em Windows 10: requer `pypiwin32`.
(Não acho que valha colocar em `requirements.txt`, pois é apenas para Windows, mas talvez no `readme.md`...)

**Comment by turicas** [comment]
Eu não uso Windows e não tenho como testar nele. Você poderia fazer essa alteração no README e criar um pull request, por favor?

**Comment by rodolfo-viana** [comment]
Feito.
